# Generated by Django 3.2.3 on 2021-05-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgoBoxofficeMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.TextField()),
                ('poster_path', models.TextField()),
                ('show_range', models.TextField()),
                ('rank', models.IntegerField()),
                ('audi', models.TextField()),
                ('sales', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='RottenMovie',
        ),
    ]
